# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "composer"
    directory: "/vendor-bin/phpunit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/psalm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/phpstan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/php-cs-fixer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/phpmd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/rector"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/infection"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/vendor-bin/deptrac"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
